# context-free grammar

<file>        ::= <form>*
<form>        ::= <expression>

<expression>  ::= <constant> | <variable>
                  | ( <condition>* cond ) # multi true-only condition
                  | ( <expression>* {and | or | eq} ) # logic operators and equality
                  | ( <expression> not )
                  | ( <expression> <expression> {lt | le | gt | ge} ) # inequality
                  | ( <expression>* {add | sub | mul} ) # operators
                  | ( <expression> <expression> {div | mod} )
                  | ( <variable> <expression> set ) # define and assignment
                  | ( <var_list> <body> lambda ) # lambda expression
                  | ( <sequence> console ) # write data
                  | ( <operand>* <operator> ) # call function

<condition>   ::= ( <text> <sequence> )
<variable>    ::= <identifier>
<var_list>    ::= <variable> | ( <variable>* )
<body>        ::= <sequence>

<sequence>    ::= <expression>+
<identifier>  ::= <initial> | <sub_sequent>*
<operator>    ::= <expression>
<operand>     ::= <expression>*
<initial>     ::= <letter>
<sub_sequent> ::= <initial> | <digit>

<letter>      ::= A | ... | Z | a | ... | z
<digit>       ::= 0 | ... | 9
